config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'individuals#new'
  resources :individuals, only: %i[index new create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/individual.rb
# frozen_string_literal: true

class Individual < ApplicationRecord
end

app/models/settings.rb
# frozen_string_literal: true

class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/individuals_controller.rb
# frozen_string_literal: true

class IndividualsController < ApplicationController
  def new
    @form = ContactForm.new
  end

  def index
    @individuals = individuals_scope
    render json: { individuals: @individuals }, status: :ok
  end

  def create
    @form = ContactForm.new(contact_form_params)
    respond_to do |format|
      if @form.save
        format.json { render json: { individual: IndividualPresenter.new(@form)._show }, status: :ok }
        format.html { redirect_to new_individual_path, flash: { notice: 'Individual contact saved' } }
      end
      format.json { render json: { error: @form.errors.full_messages.first }, status: :unprocessable_entity }
      format.html { render :new }
    end
  end

  private

  def contact_form_params
    params.require(:contact_form).permit(:name, :phone_number)
  end

  def individuals_scope
    IndividualsQuery.new.name_prefix_query(Individual.all)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/individuals/new.html.erb
<strong><%= 'Contact Form' %></strong>
<%= form_for @form, url: individuals_path do |f| %>
  
  <p id="notice"><%= notice %></p>

  <% if @form.errors.any? %>
    <%= @form.errors.full_messages %>
  <% end %>
  <br><br>

  <%= f.label :name %>
  <br>
  <%= f.text_field :name, :required => true, :pattern=>'[a-zA-Z]{1,30}', :maxlength => 20, :size=>'30', placeholder: 'Max 30 alphabet long string' %>
  <br><br>
  <%= f.label :phone_number %>
  <br>
  <%= f.text_field :phone_number, :size=>'30', :pattern=>'\d{1,12}', placeholder: 'Max 12 digit numerical value' %>
  <br><br>
  <%= f.submit id: "submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FromObject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>